{
  inputs = {
    nix = {
      url = "github:DeterminateSystems/nix-src";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    flake-parts.follows = "nix/flake-parts";

    nixpkgs.url = "github:nixos/nixpkgs";

    git-hooks-nix.url = "github:cachix/git-hooks.nix";

    treefmt-nix.url = "github:numtide/treefmt-nix";
  };

  outputs =
    inputs:
    let
      /**
        The PGO/CSPGO/BOLT variants, each optimized using profiles generated by the workloads in `profileWorkloads`
        (attribute paths into `profiles.eval` in helper.nix), from the Nix source with `patches` applied. See
        helper.nix for `extraProfileEvalArgs`.
      */
      mkOptimizedVariants =
        {
          pkgs,
          lib ? pkgs.lib,
          profileWorkloads,
          patches ? [ ],
          extraProfileEvalArgs ? [ ],
        }:
        let
          helper' = import ./helper.nix {
            inherit inputs lib pkgs;
          };
          helper =
            args:
            helper' (
              {
                inherit profileWorkloads patches extraProfileEvalArgs;
              }
              // args
            );
        in
        lib.fix (self: {
          bolt-profiling = helper {
            enableBOLTProfiling = true;
          };

          bolt = helper {
            withBOLTProfiling = self.bolt-profiling;
            enableBOLT = true;
          };

          pgo-profiling = helper {
            enablePGOProfiling = true;
          };

          pgo = helper {
            withPGOProfiling = self.pgo-profiling;
            enablePGO = true;
          };

          pgo-bolt-profiling = helper {
            withPGOProfiling = self.pgo-profiling;
            enablePGO = true;
            enableBOLTProfiling = true;
          };

          pgo-bolt = helper {
            withPGOProfiling = self.pgo-profiling;
            enablePGO = true;
            withBOLTProfiling = self.pgo-bolt-profiling;
            enableBOLT = true;
          };

          cs-pgo-profiling = helper {
            # CSPGO Profiling requires the PGO profile as well
            withPGOProfiling = self.pgo-profiling;
            enableCSPGOProfiling = true;
          };

          cs-pgo = helper {
            withCSPGOProfiling = self.cs-pgo-profiling;
            enableCSPGO = true;
          };

          cs-pgo-bolt-profiling = helper {
            withCSPGOProfiling = self.cs-pgo-profiling;
            enableCSPGO = true;
            enableBOLTProfiling = true;
          };

          cs-pgo-bolt = helper {
            withCSPGOProfiling = self.cs-pgo-profiling;
            enableCSPGO = true;
            withBOLTProfiling = self.cs-pgo-bolt-profiling;
            enableBOLT = true;
          };
        });
    in
    inputs.flake-parts.lib.mkFlake { inherit inputs; } {
      systems = [
        "aarch64-linux"
        "x86_64-linux"
      ];

      imports = [
        inputs.treefmt-nix.flakeModule
        inputs.git-hooks-nix.flakeModule
      ];

      # For consumers of this flake, e.g. to build variants of a patched Nix:
      #   inputs.nix-optimization.lib.mkOptimizedVariants {
      #     system = "x86_64-linux";
      #     profileWorkloads = [ [ "nixpkgs" "parallel" ] ];
      #     patches = [ ./my.patch ];
      #   }
      flake.lib.mkOptimizedVariants =
        { system, ... }@args:
        mkOptimizedVariants (
          removeAttrs args [ "system" ]
          // {
            pkgs = inputs.nixpkgs.legacyPackages.${system};
          }
        );

      perSystem =
        {
          config,
          lib,
          pkgs,
          ...
        }:
        {
          legacyPackages =
            let
              helper = import ./helper.nix {
                inherit inputs lib pkgs;
              };
            in
            {
              gcc =
                (inputs.nix.lib.makeComponents {
                  inherit pkgs;
                  getStdenv = builtins.getAttr "stdenv";
                }).overrideScope
                  (
                    final: _: {
                      # DetSys Nix's packaging/dependencies.nix builds boehmgc from its own fork (the `bdwgc` flake
                      # input) with its own CFLAGS; keep that and only swap the stdenv.
                      # Must use clangStdenv else we get segfaults when program is exiting if we've BOLTed the binary.
                      boehmgc =
                        (import (inputs.nix + "/packaging/dependencies.nix") {
                          inherit (inputs.nix) inputs;
                          inherit pkgs;
                          stdenv = pkgs.clangStdenv;
                        } final).boehmgc;

                      # Meson 1.12 (unlike 1.10, which DetSys pins) resolves unity-build sources in a source subdirectory
                      # named like the build directory (e.g. src/libstore/build/) relative to the build directory, so use
                      # another name.
                      mesonComponentOverrides = _: _: { mesonBuildDir = "_build"; };
                    }
                  );

              clang =
                (inputs.nix.lib.makeComponents {
                  inherit pkgs;
                  getStdenv = builtins.getAttr "clangStdenv";
                }).overrideScope
                  (
                    final: _: {
                      # DetSys Nix's packaging/dependencies.nix builds boehmgc from its own fork (the `bdwgc` flake
                      # input) with its own CFLAGS; keep that and only swap the stdenv.
                      # Must use clangStdenv else we get segfaults when program is exiting if we've BOLTed the binary.
                      boehmgc =
                        (import (inputs.nix + "/packaging/dependencies.nix") {
                          inherit (inputs.nix) inputs;
                          inherit pkgs;
                          stdenv = pkgs.clangStdenv;
                        } final).boehmgc;

                      # Meson 1.12 (unlike 1.10, which DetSys pins) resolves unity-build sources in a source subdirectory
                      # named like the build directory (e.g. src/libstore/build/) relative to the build directory, so use
                      # another name.
                      mesonComponentOverrides = _: _: { mesonBuildDir = "_build"; };
                    }
                  );

              baseline = helper { };

            }
            # Trained on single-core evaluation of a NixOS system closure.
            // mkOptimizedVariants {
              inherit lib pkgs;
              profileWorkloads = [
                [
                  "closures"
                  "gnome"
                ]
              ];
            }
            // {
              # Trained on a read-only parallel evaluation of all of Nixpkgs instead.
              nixpkgs-parallel-eval = mkOptimizedVariants {
                inherit lib pkgs;
                profileWorkloads = [
                  [
                    "nixpkgs"
                    "parallel"
                  ]
                ];
              };
            };

          pre-commit.settings.hooks = {
            # Formatter checks
            treefmt = {
              enable = true;
              package = config.treefmt.build.wrapper;
            };

            # Nix checks
            deadnix.enable = true;
            nil.enable = true;
            statix.enable = true;
          };

          treefmt = {
            projectRootFile = "flake.nix";
            programs = {
              # Nix
              nixfmt.enable = true;

              # Shell
              shellcheck.enable = true;
              shfmt.enable = true;
            };
          };
        };
    };
}
